

# @name Login
POST http://localhost:3000/api/signin
content-type: application/json

{
    "email": "john.doe@example.com",
    "password": "johndoe123"
}

###


http://localhost:3000/api/v1/product?
Cookie: {{{Login.headers.Cookie}}
###

http://localhost:3000/api/v1/orders
Cookie: {{{Login.headers.Cookie}}
###


# @
http://localhost:3000/api/v1/orders?where=id,eq,111
Cookie: {{{Login.headers.Cookie}}
###
http://localhost:3000/api/v1/orders?where=id,eq,112
Cookie: {{{Login.headers.Cookie}}

###
http://localhost:3000/api/v1/orders/111
Cookie: {{{Login.headers.Cookie}}
###


